server:
  port: 8080

spring:
  application:
    name: spring-boot-best-practices

  datasource:
    url: jdbc:mysql://root:admin@localhost:3306/testdb
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    data:
      jpa:
        repositories:
          enabled: true